import { expect, test, describe } from "bun:test";
import {
  intervalUp,
  intervalDown,
  type IntervalName,
  type PitchClass,
} from "../src";

describe("intervalUp() interval table", () => {
  const cases: [PitchClass, IntervalName, PitchClass][] = [
    // C tonic
    ["C", "unison", "C"],
    ["C", "min2", "Db"],
    ["C", "maj2", "D"],
    ["C", "min3", "Eb"],
    ["C", "maj3", "E"],
    ["C", "p4", "F"],
    ["C", "aug4", "F#"],
    ["C", "dim5", "Gb"],
    ["C", "p5", "G"],
    ["C", "min6", "Ab"],
    ["C", "maj6", "A"],
    ["C", "min7", "Bb"],
    ["C", "maj7", "B"],
    // C# tonic
    ["C#", "unison", "C#"],
    ["C#", "min2", "D"],
    ["C#", "maj2", "D#"],
    ["C#", "min3", "E"],
    ["C#", "maj3", "E#"],
    ["C#", "p4", "F#"],
    ["C#", "aug4", "Fx"],
    ["C#", "dim5", "G"],
    ["C#", "p5", "G#"],
    ["C#", "min6", "A"],
    ["C#", "maj6", "A#"],
    ["C#", "min7", "B"],
    ["C#", "maj7", "B#"],
    // Db tonic
    ["Db", "unison", "Db"],
    ["Db", "min2", "Ebb"],
    ["Db", "maj2", "Eb"],
    ["Db", "min3", "Fb"],
    ["Db", "maj3", "F"],
    ["Db", "p4", "Gb"],
    ["Db", "aug4", "G"],
    ["Db", "dim5", "Abb"],
    ["Db", "p5", "Ab"],
    ["Db", "min6", "Bbb"],
    ["Db", "maj6", "Bb"],
    ["Db", "min7", "Cb"],
    ["Db", "maj7", "C"],
    // D tonic
    ["D", "unison", "D"],
    ["D", "min2", "Eb"],
    ["D", "maj2", "E"],
    ["D", "min3", "F"],
    ["D", "maj3", "F#"],
    ["D", "p4", "G"],
    ["D", "aug4", "G#"],
    ["D", "dim5", "Ab"],
    ["D", "p5", "A"],
    ["D", "min6", "Bb"],
    ["D", "maj6", "B"],
    ["D", "min7", "C"],
    ["D", "maj7", "C#"],
    // D# tonic
    ["D#", "unison", "D#"],
    ["D#", "min2", "E"],
    ["D#", "maj2", "E#"],
    ["D#", "min3", "F#"],
    ["D#", "maj3", "Fx"],
    ["D#", "p4", "G#"],
    ["D#", "aug4", "Gx"],
    ["D#", "dim5", "A"],
    ["D#", "p5", "A#"],
    ["D#", "min6", "B"],
    ["D#", "maj6", "B#"],
    ["D#", "min7", "C#"],
    ["D#", "maj7", "Cx"],
    // Eb tonic
    ["Eb", "unison", "Eb"],
    ["Eb", "min2", "Fb"],
    ["Eb", "maj2", "F"],
    ["Eb", "min3", "Gb"],
    ["Eb", "maj3", "G"],
    ["Eb", "p4", "Ab"],
    ["Eb", "aug4", "A"],
    ["Eb", "dim5", "Bbb"],
    ["Eb", "p5", "Bb"],
    ["Eb", "min6", "Cb"],
    ["Eb", "maj6", "C"],
    ["Eb", "min7", "Db"],
    ["Eb", "maj7", "D"],
    // E tonic
    ["E", "unison", "E"],
    ["E", "min2", "F"],
    ["E", "maj2", "F#"],
    ["E", "min3", "G"],
    ["E", "maj3", "G#"],
    ["E", "p4", "A"],
    ["E", "aug4", "A#"],
    ["E", "dim5", "Bb"],
    ["E", "p5", "B"],
    ["E", "min6", "C"],
    ["E", "maj6", "C#"],
    ["E", "min7", "D"],
    ["E", "maj7", "D#"],
    // E tonic
    ["F", "unison", "F"],
    ["F", "min2", "Gb"],
    ["F", "maj2", "G"],
    ["F", "min3", "Ab"],
    ["F", "maj3", "A"],
    ["F", "p4", "Bb"],
    ["F", "aug4", "B"],
    ["F", "dim5", "Cb"],
    ["F", "p5", "C"],
    ["F", "min6", "Db"],
    ["F", "maj6", "D"],
    ["F", "min7", "Eb"],
    ["F", "maj7", "E"],
  ];
  test.each(cases)("%s + %s = %s", (start, interval, expected) => {
    expect(intervalUp(start, interval)).toBe(expected);
  });
});

describe("intervalDown() interval table", () => {
  const cases: [PitchClass, IntervalName, PitchClass][] = [
    ["C", "unison", "C"],
    ["C", "min2", "B"],
    ["C", "maj2", "Bb"],
    ["C", "min3", "A"],
    ["C", "maj3", "Ab"],
    ["C", "p4", "G"],
    ["C", "aug4", "Gb"],
    ["C", "dim5", "F#"],
    ["C", "p5", "F"],
    ["C", "min6", "E"],
    ["C", "maj6", "Eb"],
    ["C", "min7", "D"],
    ["C", "maj7", "Db"],
    // Enharmonics
    ["Ab", "maj3", "Fb"],
  ];
  test.each(cases)("%s - %s = %s", (start, interval, expected) => {
    expect(intervalDown(start, interval)).toBe(expected);
  });
});
